#!/bin/bash

DOCKER_IMAGE=${DOCKER_IMAGE:-$1}

echo Building $DOCKER_IMAGE

set -vxe

eval $(minikube docker-env)

mkdir -p tmp/dockerbuild

cp Dockerfile tmp/dockerbuild/

cd tmp/dockerbuild

echo docker-build context contains: $(find .)

#docker build -t $DOCKER_IMAGE .
imagebuilder --build-arg GITHUB_TOKEN=$GITHHUB_TOKEN -t $DOCKER_IMAGE .
docker push $DOCKER_IMAGE
